### ISSUE TITLE
Unable to install using pip

### ISSUE THREAD

**Issue by massimiliano-della-rovere** [tornado-utils/tornado-restless#12]
When I try to install Tornado-Restless using pip I get the following errors:

```
(angularjs)mader@triskelion:~$ pip search Tornado-Restless
mader@snigajakomputilo:~/Lavoro/Projects/backend$ pip search tornado-restless
Tornado-Restless          - flask-restless adopted for tornado
Tornado-Backbone          - backbone models from sqlalchemy orm for tornado-restless

(angularjs)mader@triskelion:~$ pip install Tornado-Restless
Downloading/unpacking Tornado-Restless
  Could not find any downloads that satisfy the requirement Tornado-Restless
  Some externally hosted files were ignored (use --allow-external Tornado-Restless to allow).
Cleaning up...
No distributions at all found for Tornado-Restless
Storing debug log for failure in /home/mader/.pip/pip.log

(angularjs)mader@triskelion:~$ pip install --allow-external Tornado-Restless
You must give at least one requirement to install (see "pip help install")
```

content of "/home/mader/.pip/pip.log": 
```
------------------------------------------------------------
/home/mader/.virtualenvs/angularjs/bin/pip run on Sun Mar 22 11:27:24 2015
Downloading/unpacking Tornado-Restless
  Getting page https://pypi.python.org/simple/Tornado-Restless/
  URLs to search for versions for Tornado-Restless:
  * https://pypi.python.org/simple/Tornado-Restless/
  Analyzing links from page https://pypi.python.org/simple/tornado-restless/
    Skipping link https://github.com/MartinMartimeo/tornado-restless (from https://pypi.python.org/simple/tornado-restless/); not a file
    Skipping link https://github.com/tornado-utils/tornado-restless (from https://pypi.python.org/simple/tornado-restless/); not a file
  Not searching https://github.com/MartinMartimeo/tornado-restless (from https://pypi.python.org/simple/tornado-restless/) for files because external urls are disallowed.
  Not searching https://github.com/MartinMartimeo/tornado-restless (from https://pypi.python.org/simple/tornado-restless/) for files because external urls are disallowed.
  Not searching https://github.com/MartinMartimeo/tornado-restless (from https://pypi.python.org/simple/tornado-restless/) for files because external urls are disallowed.
  Not searching https://github.com/tornado-utils/tornado-restless (from https://pypi.python.org/simple/tornado-restless/) for files because external urls are disallowed.
  Not searching https://github.com/tornado-utils/tornado-restless (from https://pypi.python.org/simple/tornado-restless/) for files because external urls are disallowed.
  Could not find any downloads that satisfy the requirement Tornado-Restless
  Some externally hosted files were ignored (use --allow-external Tornado-Restless to allow).
Cleaning up...
  Removing temporary dir /home/mader/.virtualenvs/angularjs/build...

No distributions at all found for Tornado-Restless
Exception information:
Traceback (most recent call last):
  File "/home/mader/.virtualenvs/angularjs/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/home/mader/.virtualenvs/angularjs/local/lib/python2.7/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/mader/.virtualenvs/angularjs/local/lib/python2.7/site-packages/pip/req.py", line 1177, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/home/mader/.virtualenvs/angularjs/local/lib/python2.7/site-packages/pip/index.py", line 277, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for Tornado-Restless
```

**Comment by westover** [comment]
+1 would love to use this package as is but can't install with pip
